### ISSUE TITLE
What's the difference between this and fzf-tab?

### ISSUE THREAD

**Issue by matru** [lincheney/fzf-tab-completion#108]
Just wondering, since they seem do to the same thing. 

I am talking about this plugin: https://github.com/Aloxaf/fzf-tab

**Comment by lincheney** [comment]
Yes, they do a lot of the same thing (generic zsh completion using fzf).

I'd say https://github.com/Aloxaf/fzf-tab in general has more features like colours, groups etc (even some things like some of the keybind actions this repo has now first appeared in `fzf-tab`)

The things this repo has over fzf-tab that I can think of are possibly better support for some ZSH completers (e.g. `_approximate` completer is supported here but does not appear to be supported in fzf-tab? not actually sure `https://github.com/Aloxaf/fzf-tab/issues/56`);
and the completion candidates are streamed to fzf rather than waiting for the end (see `https://github.com/Aloxaf/fzf-tab/issues/65#issuecomment-602217690`).
This last one is probably the main deal breaker for me, being able to use fzf and select items without having to wait for the whole completion process to finish is very useful when there are many completion candidates and/or generating completions is slow (e.g. when I am completing EC2 instance ids for the AWS CLI which requires paginated network calls).

**Comment by matru** [comment]
Hey, thank you a lot for your thorough response! I will check these things out. Could you perhaps also let me know why one would opt for these plugins instead of using the official implementation from fzf?

**Comment by lincheney** [comment]
Hi, the key thing about these plugins is that they wrap the existing zsh completion mechanism.
Any command that has the ZSH tab completion defined in the usual way will "just work".
The official fzf completion by contrast overrides the tab completion of specific commands to support fzf.

If you browse through the official fzf completion script for zsh https://github.com/junegunn/fzf/blob/master/shell/completion.zsh you will see that it has support for completing telnet, ssh, export and a few other commands. But what it doesn't do is support completion for arbitrary commands, each command you want to support requires you to write a `_fzf_complete_XYZ` function (see also https://github.com/junegunn/fzf?tab=readme-ov-file#custom-fuzzy-completion). If you installed a new CLI tool that came with zsh tab completion support, it would not work out of the box with fzf, until you had defined that function.
