### ISSUE TITLE
missing icons in fzf list

### ISSUE THREAD

**Issue by laur89** [lincheney/fzf-tab-completion#16]
Some icon (?) is rendering oddly: https://i.imgur.com/7ZrQCH8.png, any idea what's going on?
Don't see this in other fzf interfaces.

OS: debian testing
shell: bash version 5.0.18(1)-release
fzf-tab-completion: `527ac6c`
fzf: `0.23.1 (fc7630a)`
terminal: `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`
font settings:
```
URxvt.font: xft:Terminess Powerline:pixelsize=14:antialias=false:hinting=false:autohint=false, xft:TerminessTTF Nerd Font Mono:pixelsize=18:antialias=false:hinting=false:autohint=false
URxvt.boldFont: xft:Terminess Powerline:style=bold:pixelsize=14:antialias=false:hinting=false:autohint=false, xft:TerminessTTF Nerd Font Mono:bold:pixelsize=18:antialias=false:hinting=false:autohint=false
```

**Comment by lincheney** [comment]
how are you getting icons into your list?

**Comment by laur89** [comment]
How do you mean?
I'm using powerline fonts from [here](https://github.com/powerline/fonts) - should nerd fonts (or something third) be used instead?

**Comment by lincheney** [comment]
ah sorry, I misunderstood your issue
I think is the same as https://github.com/lincheney/fzf-tab-completion/issues/4#issuecomment-570557351, except I only ever applied the fix for zsh, not bash
I've pushed https://github.com/lincheney/fzf-tab-completion/commit/d62e6ce6755bba2c07e9fe147779d68f19a80170
can you try that and see if it fixes the issue?
