### ISSUE TITLE
Defaults missing for path completion

### ISSUE THREAD

**Issue by csdvrx** [lincheney/fzf-tab-completion#32]
In bash, cd followed by tab usually shows available files or directories: try for example 'cd /usr/lo' then tab to complete to /usr/local then tab tab to list /usr/local/bin etc.

Following the install instructions, all I get is:
fzf-bash-completion.sh: line 291: complete: : no completion specification

tabbing to complete filenames or path is very basic, and should be supported out of the box

**Comment by lincheney** [comment]
Can you give me the output of running `complete -p ''` and also `complete -p`
Also, what version of bash are you running

**Comment by lincheney** [comment]
hi, I did some troubleshooting and I believe this happens when you have no actual bash completion loaded so it falls back to the readline completion instead
I've made https://github.com/lincheney/fzf-tab-completion/commit/f3695ce60e1495fec317e54b04c3cc169e34a0e9  to simulate that fallback readline completion, can you try it out and let me know if it fixes your issue
