### ISSUE TITLE
Is multi-select possible?

### ISSUE THREAD

**Issue by siulkilulki** [lincheney/fzf-tab-completion#55]
Is multi-select not possible or I'm missing something?

**Comment by lincheney** [comment]
what shell are you using?
ZSH should work (mostly; there's some bugs but they are due to ZSH itself)
I just tried with bash and I notice there appears to be a bug where it adds extra escaping.
Is that what you are seeing?

**Comment by lincheney** [comment]
I've pushed https://github.com/lincheney/fzf-tab-completion/commit/6464769132530b2dd4c4c2abdb0e69874f40dc25 which should fix bash multi select issues.
For zsh, I've not been having issues.
Otherwise, please make sure you have applied the `-m` or `--multi` flag to your `$FZF_DEFAULT_OPTS` or `$FZF_COMPLETION_OPTS` etc.
