### ISSUE TITLE
[readline] missing install steps ?

### ISSUE THREAD

**Issue by rockandska** [lincheney/fzf-tab-completion#8]
Hi,

I was expecting to try the readline hack since it is a very cool feature !
But unfortunately I'm not able to have a functional installation.
Did I miss something ?
```shell
$ env -i PATH=$PATH HOME=$HOME bash --norc --noprofile
bash-4.4$ cat .inputrc
$include function rl_custom_complete /tmp/rl_custom_function/fzf-tab-completion/readline/target/release/librl_custom_complete.so
"\t": rl_custom_complete
bash-4.4$ ls /tmp/rl_custom_function/target/release/librl_custom_function.so
/tmp/rl_custom_function/target/release/librl_custom_function.so
bash-4.4$ export LD_PRELOAD=/tmp/rl_custom_function/target/release/librl_custom_function.so
bash-4.4$ ls /tmp/rl_custom_function/fzf-tab-completion/readline/bin
rl_custom_complete
bash-4.4$ export PATH="/tmp/rl_custom_function/fzf-tab-completion/readline/bin:${PATH}"
bash-4.4$  
``` 

Regards

**Comment by lincheney** [comment]
ahh you're entirely correct! My instructions are wrong, `$LD_PRELOAD` needs to be set before running bash.
I've actually got it set in my `~/.pam_environment` which is why it always worked for me.

Are you able to try that out? Or `/etc/environment` or a systemd env var should also work.
Or if you just want to give it a test run, just run another `bash` shell after doing your `export LD_PRELOAD=...`

**Comment by mstr3336** [comment]
The readline hack isn't working for me either - I was excited to try it w/ other readline consoles, like R when working on remote systems but no dice.
